### PR TITLE
WIP: New CLI foundations

### PR DESCRIPTION
**Pull request by Thimoteus**
This took a while because I was trying to find a principled way to deal with mutually exclusive commands (for example `chanterelle init` is mutually exclusive with `chanterelle test`); the old yargs setup didn't work because its applicative interface doesn't have an `Alt` instance, so the old code basically dealt with the raw CLI options passed in (what's the point of using yargs then?) I wasn't able to find a way to deal with alternatives and keep all the properties of the parser I wanted (monoidal analysis via free applicatives, errors accumulated in a semigroup, etc) so what I came up with is still a little ad-hoc, but IMO still much better than repeatedly unconsing the option stream.

### CODE REVIEW

**Comment by blinky3713** [comment]
cool, will take a close look soon. A first glance yields a few comments, but feel free to not answer while it's still WIP. I just want to make sure we don't diverge too far in what's going on.

1.  While the parser library developed here seems pretty cool, it probably doesn't belong in this repository, but could be included as a dependency if it was a library you were planning on maintaining.

2. I'm confused why `purescript-parsing`, `purescript-string-parsers` , or `purescript-simple-parser` (yours) are insufficient for this task. Particularly the first which I have more familiarity with as it's basically a port of the haskell `parsec` library. This library is powerful enough to perform the parsing of the PureScript language itself and basically any grammar that anyone uses in the wild.

**Comment by Thimoteus** [comment]
1. I would have done that, except that this project is still on 0.11.7, and I wanted to avoid having a public-facing library that either a) only supports 0.11.7 when most people are using 0.12, or b) has to deal with supporting two compiler versions simultaneously.
2. Sufficient, yes, but they all are pretty much the same in that they're monadic parser libraries, which means they give you a lot of extra, often unneeded, power at the expense of nicer, actually useful properties. For example, the paper on free applicatives specifically uses command line parsing as an example, because you can for instance use monoidal analysis to generate the help message from your parsers. You can't do that with a free monad because the bind operator requires you to to actually run the program in order to determine what path it takes. I'm also using semigroup validation to collect multiple errors (which is, strictly applicative and not monadic), whereas otherwise it would bail out and report the first error it finds.

**Comment by iostat** [comment]
Hey! I see this is still WIP with no updates in a while. Just wanted to check in and see if there’s anything else relating to this PR in the works that just hasn’t been pushed yet or just any other updates in general. 

I also kinda want to echo @blinky’s concern about the inclusion of the parsing library in this PR. It seems like it would end up being some code that would need to be maintained which is secondary to Chanterelle itself. Would it be possible to at least extract it out to some repo that could then be pulled in as a bower dep or something? We’re hoping to move to 0.12 at some point in the future as well with Chanterelle, and until we could do so it’d be nice to not have to worry about the implications of maintaining additional code in the meantime, especially if this is just a backport and has some API parity with an 0.12 equivalent.

**Comment by Thimoteus** [comment]
Hey, sorry to go MIA but I had some personal stuff come up so I don't think I'll have the time necessary to finish this off for a while, so it's probably best to find someone else.

**Pull request closed without merging**
